parent_button_icon:
  type: string
  default: "plus"
  description: |
    <a target="_blank" href="https://fontawesome.com/v5.15/icons?d=gallery&m=free">FontAwesome</a> icon name...

new_topic_icon:
  type: string
  default: "comment"
  description: |
    <a target="_blank" href="https://fontawesome.com/v5.15/icons?d=gallery&m=free">FontAwesome</a> icon name...

custom_option_icon:
  type: string
  default: "envelope"
  description: |
    <a target="_blank" href="https://fontawesome.com/v5.15/icons?d=gallery&m=free">FontAwesome</a> icon name...

custom_option_action:
  type: enum
  default: "privateMessage"
  choices:
    - "privateMessage"
    - "createTopic"

pm_recipients:
  type: list
  default: "moderators"

hide_pm_recipients:
  type: bool
  default: false
  description: hides recipients from PM composer, unless user is a staff member

custom_option_tags:
  type: list
  default: ""

custom_option_category:
  type: integer
  default: 0
  min: 0
  max: 999
  description: accepts a category id; you can find the category id by looking for the number in the URL when you navigate to a category's topic list

svg_icons:
  default: ""
  type: "list"
  list_type: "compact"
  description: Used for adding Font Awesome icons that aren't already part of Discourse's subset
