parent_button_icon:
  type: string
  default: "plus"

new_topic_icon:
  type: string
  default: "comment"

custom_option_icon:
  type: string
  default: "envelope"

custom_option_action:
  type: enum
  default: "privateMessage"
  choices:
    - "privateMessage"
    - "createTopic"

pm_recipients:
  type: list
  default: "moderators"

hide_pm_recipients:
  type: bool
  default: false

custom_option_tags:
  type: list
  default: ""

custom_option_category:
  type: integer
  default: 0
  min: 0
  max: 999

hijack_pm_toggle:
  default: false

composer_pm_toggle:
  default: false

svg_icons:
  default: ""
  type: "list"
  list_type: "compact"
